### PR TITLE
Lint

### PR DESCRIPTION
**Pull request by tannewt**

### CODE REVIEW

**Review by makermelissa — APPROVED** [review]
Looks good, not tested.

**Comment by dhalbert** [comment]
I am finding some problems, testing on hardware, so hold on.

**Comment by tannewt** [comment]
@dhalbert I had the services import wrong so make sure you have that. (Just tested it myself.)

**Review by dhalbert — CHANGES_REQUESTED** [review]
In `adafruit_ble_magic_light.py`,

This line:
`from adafruit_ble.service import Service`

needs plural `.services`:
`from adafruit_ble.services import Service`

After that change:
Does not work with beta.1, does work with circuitpython commit `f2b1aeeed`. I'm having trouble building the tip of master.

**Comment by dhalbert** [comment]
yup, we both found the same thing.

**Review by dhalbert — APPROVED** [review]
Tested in a lamp, now works! I assume I am spooking out people passing in the street.

**Pull request merged**
